### ISSUE TITLE
Incompatible With Firefox

### ISSUE THREAD

**Issue by thankyougrass** [AWikia/SkinEvelution#117]
I was previously using this skin for a Miraheze wiki, but recently it began displaying a blank page with an "Unsupported Configuration" error whenever I attempted to access the wiki using Firefox 127.0. I used Safari to properly load the wiki and switched the skin, and the error stopped showing up.

**Comment by HM100** [comment]
This issue has been patched as of 155.0.1 but Miraheze uses 154.0.0, which it along with 155.0.0 has a bugged minimum Firefox version requirement that it is set to an unachievable ones (Requirement was accidentally set to 1115 instead of 114). As it is not repro in latest Evelution, closing with invalid status. This will fade out on Miraheze once it gets to latest ones.
